ci: Update Poetry version in build workflow
When using 1.1.15 on Python 3.12+ we get an error when building:

ModuleNotFoundError: No module named 'six.moves'

Since we dropped Python 3.6 support, we no longer need to use this old
1.1.15 version anyway, so update to the latest 1.x version. 2.0 should
ok too, but it brings more deprecations due to PEP 621 support.